### ISSUE TITLE
_gen_msg_values does not check for lists

### ISSUE THREAD

**Issue by ksomml** [wentasah/rosbag2csv#1]
The function `def _gen_msg_values(msg, prefix=""):` does not check if the message is a list of messages before using ..get_fields_and_field_types().items() and thus crashes.

Code from repository:
https://github.com/wentasah/rosbag2csv/blob/15b731a7fcc4906f503ad380ff280ad9a70339f1/rosbag2csv.py#L46-L47
Example:
_Custom message type IMUDataArray and IMUData is used._
IMUDataArray consists of a timestamp and a list of IMUData messages.

Structure:
```
IMUDataArray
- timestamp
- IMUData
-- imu_1
--- orientation
--- acceleration
--- magnetometer
-- imu_2
--- orientation
--- acceleration
--- magnetometer
-- imu_...
...
```
Debugger before crash:
![image](https://github.com/user-attachments/assets/48d578ed-e2a9-451d-804f-f53c087df78e)

Logs:
```
[...]
  File "ros2bag_to_csv.py", line 111, in <module>
    dump_bag(sys.argv[1])
  File "ros2bag_to_csv.py", line 92, in dump_bag
    fields = [field for field, val in _gen_msg_values(msg)
  File "ros2bag_to_csv.py", line 92, in <listcomp>
    fields = [field for field, val in _gen_msg_values(msg)
  File "ros2bag_to_csv.py", line 59, in _gen_msg_values
    for key, val in _gen_msg_values(getattr(msg, field),
  File "ros2bag_to_csv.py", line 54, in _gen_msg_values
    for field, type in msg.get_fields_and_field_types().items():
AttributeError: 'list' object has no attribute 'get_fields_and_field_types'
```

**Comment by wentasah** [comment]
Hi and thanks for reporting the problems. 

Can you test whether the current version works for you? If not, can you send some problematic bag?

**Comment by ksomml** [comment]
Can confirm that the bag is parsed properly and the expected .csv file is generated. Thanks a lot!
